name: Publish Package
on:
    release:
        types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v3

            - name: Install Dependencies
              run: pnpm install -r --frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Typecheck
              run: pnpm run typecheck

            - name: Prettier Check
              run: pnpm run prettiercheck

            - name: Circular Dependencies Check
              run: pnpm run circularcheck

            - name: Test
              run: pnpm run test

            - name: Publish
              run: pnpm publish --access public --no-git-checks # Disable checks because this will run on a headless release
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
